import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner"
import { Suspense } from "react";
import Footer from "@/components/Footer";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800",]
});


export const metadata: Metadata = {
  title: "Shivay Safar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} ${sora.className} antialiased`}
      >
        <main>
          <Navbar />
          <Suspense>
            {children}
          </Suspense>
          <Footer />
        </main>
        <Toaster />
      </body>
    </html>
  );
}
